name: eipoca
description: new chat app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  advstory: ^0.2.1
  animated_splash_screen: ^1.3.0
  any_link_preview: ^3.0.1
  avatars: ^3.0.2
  cached_network_image: ^3.2.3
  chat_bubbles: ^1.5.0
  cloud_firestore: ^4.8.2
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.7
  editable_image: ^2.0.0
  encrypt: ^5.0.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.6
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_dialogs: ^3.0.0
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.0.4
  flutter_launcher_icons: ^0.13.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_windowmanager: ^0.2.0
  form_validator: ^2.1.1
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  iconsax: ^0.0.8
  image_picker: any
  jiffy: ^6.2.1
  localstore: ^1.3.5
  ndialog: ^4.3.1
  network_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  photo_view: ^0.14.0
  provider: ^6.0.5
  rounded_loading_button: ^2.1.0
  salomon_bottom_bar: ^3.3.2
  select_dialog: ^2.0.1
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  story_view: ^0.15.0
  timeago: ^3.5.0
  url_launcher: ^6.1.12
  uuid: ^3.0.7
  velocity_x: ^4.1.0
  vs_story_designer: ^2.0.1
  xid: ^1.0.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
